pre_trained_model:
  project: stochastic_navier_stokes
  name: stochastic_interpolant_small

obs_operator:
  _target_: scisi.likelihood_models.observation_operators.LinearObservationOperator
  # type: random
  # percent_obs: 0.05
  # percent_obs: 0.015625
  type: grid
  skip_grid: 8

likelihood_model:
  _target_: scisi.likelihood_models.gaussian_likelihood.InterpolantGaussianLikelihood
  variance: 0.0025
  ensemble_size: 25

posterior_model:
  _target_: scisi.posterior_models.stochastic_interpolant_posterior.StochasticInterpolantPosterior
