experiment_tracking:
  project: knmi

len_field_history: 5

preprocesser:
  _target_: scisi.preprocessing.preprocessor.Preprocesser
  base:
    mean:
      - 282.1561
    std:
      - 19.090252
  target:
    mean:
      - 282.1561
    std:
      - 19.090252
  field_cond:
    mean:
      - 282.15598
    std:
      - 17.836073

# Data
train_data:
  # Dataloader
  _target_: torch.utils.data.DataLoader
  batch_size: 64
  shuffle: True
  num_workers: 4
  # Dataset
  dataset:
    _target_: scisi.data.datasets.KNMIDataset
    paths:
      - /export/scratch2/ntm/SciGenML/data/knmi/
    files:
      - sim_1.npz
      - sim_2.npz
      - sim_3.npz
      - sim_4.npz
      - sim_5.npz
    len_field_history: ${len_field_history}
    save_in_memory: False
    cache_dir: /export/scratch1/ntm/postdoc/scientific-stochastic-interpolants/cache/knmi/train
    use_exisiting_cache: True
    starting_time: null
    ending_time: null

val_data:
  _target_: torch.utils.data.DataLoader
  batch_size: 64
  shuffle: False
  num_workers: 4
  dataset:
    _target_: scisi.data.datasets.KNMIDataset
    paths:
      - /export/scratch2/ntm/SciGenML/data/knmi/
    files:
      - sim_8.npz
      - sim_9.npz
    len_field_history: ${len_field_history}
    save_in_memory: False
    cache_dir: /export/scratch1/ntm/postdoc/scientific-stochastic-interpolants/cache/knmi/val
    use_exisiting_cache: True
    starting_time: null
    ending_time: null

test_data:
  _target_: scisi.data.datasets.KNMIDataset
  paths:
    - /export/scratch2/ntm/SciGenML/data/knmi/
  files:
    - sim_10.npz
    # - sim_11.npz
    # - sim_12.npz
  len_field_history: ${len_field_history}
  train_or_test: test
  save_in_memory: True
  starting_time: null
  ending_time: null

model:
  _target_: scisi.models.follmer_stochastic_interpolant.FollmerStochasticInterpolant
  interpolation:
    _target_: scisi.models.interpolations.QuadraticStochasticInterpolation
    gamma_multiplier: 0.1
    wiener_process: true
  drift_model:
    _target_: scisi.architectures.pde_transformer.PDETransformerWrapper
    in_channels: 1 # number of channels in the input
    out_channels: 1 # number of channels in the output
    len_field_history: 3 # number of field history steps
    type: PDE-B # type of the PDE transformer. S for small, B for medium, L for large
    patch_size: 4 # patch size
    periodic: true # whether to use periodic padding
    carrier_token_active: false # whether to use carrier tokens
    field_cond_channels: null # number of channels in the field conditional input

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0001
  weight_decay: 0.0000001

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 500
  eta_min: 0.00001

loss_fn:
  _target_: torch.nn.MSELoss

trainer:
  _target_: scisi.training.trainer.Trainer
  num_epochs: 1000
  device: cuda
  early_stopping:
    _target_: scisi.training.trainer.EarlyStopping
    patience: 50
  max_grad_norm: 5.0
  mixed_precision_warmup: 100
