pre_trained_model:
  project: stochastic_navier_stokes
  # name: warm-root-42
  # name: valiant-petal-41
  # name: sincere-ridge-38
  # name: resourceful-plain-37
  # name: quirky-cave-36
  # name: optimistic-spring-34
  # name: mysterious-crane-57
  # name: spirited-bear-62
  # name: vivid-otter-65
  # name: artful-hare-68
  name: stochastic_interpolant_small

obs_operator:
  _target_: scisi.likelihood_models.observation_operators.LinearObservationOperator
  type: random
  # percent_obs: 0.05
  percent_obs: 0.015625
  # type: grid
  # skip_grid: 8

likelihood_model:
  # _target_: scisi.likelihood_models.gaussian_likelihood.KalmanInterpolantGaussianLikelihood
  # _target_: scisi.likelihood_models.gaussian_likelihood.InterpolantGaussianLikelihood
  # _target_: scisi.likelihood_models.gaussian_likelihood.SpatialInterpolantGaussianLikelihood
  _target_: scisi.likelihood_models.gaussian_likelihood.FlowdasGaussianLikelihood
  variance: 0.0025
  ensemble_size: 25
  # interpolant:
  #   # _target_: scisi.models.interpolations.QuadraticStochasticInterpolation
  #   _target_: scisi.models.interpolations.LinearStochasticInterpolation
  #   gamma_multiplier: 1.0
  #   wiener_process: true

posterior_model:
  _target_: scisi.posterior_models.stochastic_interpolant_posterior.StochasticInterpolantPosterior
  # _target_: scisi.posterior_models.stochastic_interpolant_posterior.StochasticInterpolantParticleFlowPosterior
