pre_trained_model:
  project: stochastic_navier_stokes
  name: sincere-ridge-38
  # name: resourceful-plain-37
  # name: quirky-cave-36
  # name: optimistic-spring-34

obs_operator:
  _target_: scisi.likelihood_models.observation_operators.LinearObservationOperator
  obs_indices:
    _target_: scisi.likelihood_models.observation_operators.get_grid_indices
    height: 128
    width: 128
    skip_grid: 4
    start_grid: 0

likelihood_model:
  _target_: scisi.likelihood_models.gaussian_likelihood.MultivariateGaussianLikelihood
  variance: 0.0025

posterior_model:
  _target_: scisi.posterior_models.stochastic_interpolant_posterior.StochasticInterpolantPosterior
