# Data
data:
  # Dataloader
  _target_: torch.utils.data.DataLoader
  batch_size: 10
  shuffle: True
  # Dataset
  dataset:
    _target_: scisinterpolant.data.datasets.StochasticNavierStokesDataset
    paths:
      - data/stochastic_navier_stokes
    files:
      - data.npz
    len_history: 2


model:
  _target_: scisinterpolant.models.follmer_stochastic_interpolant.FollmerStochasticInterpolant
  interpolation:
    _target_: scisinterpolant.models.interpolations.QuadraticStochasticInterpolation
  drift_model:
    _target_: scisinterpolant.architectures.u_net.UNet
    in_channels: 1 # number of channels in the input
    out_channels: 5 # number of channels in the output
    hidden_channels: [16, 32, 64, 128] # number of channels in the hidden layers
    cond_dim: 1 # dimension of the scalar conditional input, this is typically pseudo time
    cond_embedding_dim: 4 # dimension of the scalar conditional embedding
    field_cond_channels: 2 # number of channels in the field conditional input
    pars_cond_dim: null # dimension of the pars conditional input, E.g. Reynolds number, viscosity, etc.
    pars_cond_embedding_dim: null # dimension of the pars conditional embedding
    multiplier: 2 # multiplier for the number of channels in the hidden layers in the conv next blocks
    num_blocks: 2 # number of convnext blocks per layer
