pre_trained_model:
  project: udales
  # name: kind-sky-8
  name: flow_matching_small

obs_operator:
  _target_: scisi.likelihood_models.observation_operators.LinearObservationOperator
  # type: grid
  # percent_obs: 0.10
  type: grid
  skip_grid: 8

likelihood_model:
  _target_: scisi.likelihood_models.guidance.GuidanceGaussianLikelihood
  # _target_: scisi.likelihood_models.gaussian_likelihood.FlowdasGaussianLikelihood
  variance: 0.0025
  ensemble_size: 25

posterior_model:
  _target_: scisi.posterior_models.flow_matching_posterior.FlowMatchingPosterior
