pre_trained_model:
  project: weather
  name: dainty-sunset-0

obs_operator:
  _target_: scisi.likelihood_models.observation_operators.LinearObservationOperator
  type: random
  percent_obs: 0.1
  # obs_indices:
  #   _target_: scisi.likelihood_models.observation_operators.get_grid_indices
  #   height: 128
  #   width: 128
  #   skip_grid: 2
  #   start_grid: 0

likelihood_model:
  _target_: scisi.likelihood_models.gaussian_likelihood.MultivariateGaussianLikelihood
  variance: 0.0025

posterior_model:
  _target_: scisi.posterior_models.stochastic_interpolant_posterior.StochasticInterpolantPosterior
