experiment_tracking:
  project: weather

len_field_history: 7

preprocesser:
  _target_: scisi.preprocessing.preprocessor.Preprocesser
  base:
    mean:
      - 21.9577
    std:
      - 41.2952
  target:
    mean:
      - 21.9577
    std:
      - 41.2952

# Data
train_data:
  # Dataloader
  _target_: torch.utils.data.DataLoader
  batch_size: 8
  shuffle: True
  num_workers: 4
  # Dataset
  dataset:
    _target_: scisi.data.datasets.WeatherDataset
    paths:
      - /export/scratch2/ntm/SciGenML/data/weather_npz/
    files:
      - "2017/random_0901_1231.npz"
      - "2017/random_0501_0831.npz"
      - "2017/storm_0701_1231.npz"
      - "2017/storm_0101_0630.npz"
      - "2018/random_0901_1231.npz"
      - "2018/random_0501_0831.npz"
      - "2018/random_0101_0430.npz"
      - "2018/storm_0701_1231.npz"
      - "2018/storm_0101_0630.npz"
      # - "2019/random_0901_1231.npz"
      # - "2019/random_0501_0831.npz"
      - "2019/random_0101_0430.npz"
      # - "2019/storm_0701_1231.npz"
      # - "2019/storm_0101_0630.npz"
    len_field_history: ${len_field_history}
    save_in_memory: False
    cache_dir: /export/scratch1/ntm/postdoc/scientific-stochastic-interpolants/cache/weather/train
    use_exisiting_cache: True
    starting_time: null
    ending_time: null

val_data:
  _target_: torch.utils.data.DataLoader
  batch_size: 8
  shuffle: False
  num_workers: 4
  dataset:
    _target_: scisi.data.datasets.WeatherDataset
    paths:
      - /export/scratch2/ntm/SciGenML/data/weather_npz/
    files:
      # - "2017/random_0901_1231.npz"
      # - "2017/random_0501_0831.npz"
      # - "2017/storm_0701_1231.npz"
      # - "2017/storm_0101_0630.npz"
      # - "2018/random_0901_1231.npz"
      # - "2018/random_0501_0831.npz"
      # - "2018/random_0101_0430.npz"
      # - "2018/storm_0701_1231.npz"
      # - "2018/storm_0101_0630.npz"
      # - "2019/random_0901_1231.npz"
      - "2019/random_0501_0831.npz"
      # - "2019/random_0101_0430.npz"
      - "2019/storm_0701_1231.npz"
      # - "2019/storm_0101_0630.npz"
    len_field_history: ${len_field_history}
    save_in_memory: False
    cache_dir: /export/scratch1/ntm/postdoc/scientific-stochastic-interpolants/cache/weather/val
    use_exisiting_cache: True
    starting_time: null
    ending_time: null

test_data:
  _target_: scisi.data.datasets.WeatherDataset
  paths:
    - /export/scratch2/ntm/SciGenML/data/weather_npz/
  files:
      # - "2017/random_0901_1231.npz"
      # - "2017/random_0501_0831.npz"
      # - "2017/storm_0701_1231.npz"
      # - "2017/storm_0101_0630.npz"
      # - "2018/random_0901_1231.npz"
      # - "2018/random_0501_0831.npz"
      # - "2018/random_0101_0430.npz"
      # - "2018/storm_0701_1231.npz"
      # - "2018/storm_0101_0630.npz"
      - "2019/random_0901_1231.npz"
      # - "2019/random_0501_0831.npz"
      # - "2019/random_0101_0430.npz"
      # - "2019/storm_0701_1231.npz"
      # - "2019/storm_0101_0630.npz"
  len_field_history: ${len_field_history}
  train_or_test: test
  save_in_memory: True
  starting_time: null
  ending_time: null

model:
  _target_: scisi.models.follmer_stochastic_interpolant.FollmerStochasticInterpolant
  interpolation:
    _target_: scisi.models.interpolations.QuadraticStochasticInterpolation
    gamma_multiplier: 0.1
    wiener_process: true
  drift_model:
    _target_: scisi.architectures.pde_transformer.PDETransformerWrapper
    in_channels: 1 # number of channels in the input
    out_channels: 1 # number of channels in the output
    len_field_history: ${len_field_history} # number of field history steps
    type: PDE-B # type of the PDE transformer. S for small, B for medium, L for large
    patch_size: 4 # patch size
    periodic: false # whether to use periodic padding
    carrier_token_active: false # whether to use carrier tokens
    field_cond_channels: null # number of channels in the field conditional input

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0001
  weight_decay: 0.000001

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 250
  eta_min: 0.00001
  # _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  # T_0: 50
  # T_mult: 1
  # eta_min: 0.00001

loss_fn:
  _target_: torch.nn.MSELoss

trainer:
  _target_: scisi.training.trainer.Trainer
  num_epochs: 1000
  device: cuda
  early_stopping:
    _target_: scisi.training.trainer.EarlyStopping
    patience: 50
  gradient_clipper:
    _target_: scisi.training.gradient_clipping.EmaGradientClipper
    ema_coef1: 0.9
    ema_coef2: 0.99
    max_norm_ratio: 2.0
    clip_norm_ratio: 1.1
  mixed_precision_warmup: 200
