name: flowdas
checkpoint_name: stochastic_interpolant_small
stepper: sde
diffusion_term: null

likelihood_model:
  _target_: scisi.likelihood_models.gaussian_likelihood.FlowdasGaussianLikelihood

posterior_model:
  _target_: scisi.posterior_models.stochastic_interpolant_posterior.StochasticInterpolantPosterior
  resample: false
