name: si
stepper: sde
diffusion_term:
  multiplier: 1.0

likelihood_model:
  _target_: scisi.likelihood_models.gaussian_likelihood.InterpolantGaussianLikelihood

posterior_model:
  _target_: scisi.posterior_models.stochastic_interpolant_posterior.StochasticInterpolantPosterior
  resample: false
